export default {
    property: {
        list: {
            1: {
                id: 1,
                address: '123 abc st',
                city: 'cowabunga',
                state: 'pq',
                zip: '12345',
                description:
                    'Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium',
                canHaveChildren: true,
                propertyType: 'residential',
                floors: 2,
                beds: 3,
                baths: 3,
                amenities: [
                    'pool',
                    'gym',
                    'spa',
                    'internet',
                    'trash',
                    'sewage',
                    'cable',
                    'free food',
                ],
                price: '123456.78',
            },
            2: {
                id: 2,
                address: '123 abc st',
                city: 'cowabunga',
                state: 'pq',
                zip: '12345',
                description:
                    'Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium',
                canHaveChildren: true,
                propertyType: 'residential',
                floors: 2,
                beds: 3,
                baths: 3,
                amenities: [
                    'pool',
                    'gym',
                    'spa',
                    'internet',
                    'trash',
                    'sewage',
                    'cable',
                    'free food',
                ],
                price: '123456.78',
            },
            3: {
                id: 3,
                address: '123 abc st',
                city: 'cowabunga',
                state: 'pq',
                zip: '12345',
                description:
                    'Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium',
                canHaveChildren: true,
                propertyType: 'residential',
                floors: 2,
                beds: 3,
                baths: 3,
                amenities: [
                    'pool',
                    'gym',
                    'spa',
                    'internet',
                    'trash',
                    'sewage',
                    'cable',
                    'free food',
                ],
                price: '123456.78',
            },
            4: {
                id: 4,
                address: '123 abc st',
                city: 'cowabunga',
                state: 'pq',
                zip: '12345',
                description:
                    'Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium',
                canHaveChildren: true,
                propertyType: 'residential',
                floors: 2,
                beds: 3,
                baths: 3,
                amenities: [
                    'pool',
                    'gym',
                    'spa',
                    'internet',
                    'trash',
                    'sewage',
                    'cable',
                    'free food',
                ],
                price: '123456.78',
            },
            5: {
                id: 5,
                address: '123 abc st',
                city: 'cowabunga',
                state: 'pq',
                zip: '12345',
                description:
                    'Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium',
                canHaveChildren: true,
                propertyType: 'residential',
                floors: 2,
                beds: 3,
                baths: 3,
                amenities: [
                    'pool',
                    'gym',
                    'spa',
                    'internet',
                    'trash',
                    'sewage',
                    'cable',
                    'free food',
                ],
                price: '123456.78',
            },
            6: {
                id: 6,
                address: '123 abc st',
                city: 'cowabunga',
                state: 'pq',
                zip: '12345',
                description:
                    'Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium',
                canHaveChildren: true,
                propertyType: 'residential',
                floors: 2,
                beds: 3,
                baths: 3,
                amenities: [
                    'pool',
                    'gym',
                    'spa',
                    'internet',
                    'trash',
                    'sewage',
                    'cable',
                    'free food',
                ],
                price: '123456.78',
            },
        },
        active: {
            // default shape
            id: null,
            address: null,
            city: null,
            state: null,
            zip: null,
            description: null,
            canHaveChildren: null,
            propertyType: null,
            floors: null,
            beds: null,
            baths: null,
            amenities: null,
            price: null,
        },
    },

    modal: {},
    auth: {
        isLoading: null,
        status: null,
        error: {
            message: null,
        },
    },
};
